"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import { Rubik, IBM_Plex_Mono } from "next/font/google";
import styles from "./page.module.css";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--landing-font-core",
});

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--landing-font-numeric",
});

type Lang = "en" | "he";

interface Copy {
  overline: string;
  h1a: string;
  h1b: string;
  heroSub: string;
  badge: string;
  betaNote: string;
  whatOverline: string;
  whatBody: string;
  howOverline: string;
  s1t: string;
  s1b: string;
  s2t: string;
  s2b: string;
  s3t: string;
  s3b: string;
  studioOverline: string;
  studioTitle: string;
  studioBody: string;
  st1t: string;
  st1b: string;
  st2t: string;
  st2b: string;
  st3t: string;
  st3b: string;
  st4t: string;
  st4b: string;
  shotsOverline: string;
  skipToContent: string;
  langGroupLabel: string;
  shotsRegionLabel: string;
  footStatus: string;
  footContact: string;
  footLegal: string;
  privacy: string;
  terms: string;
  accessibility: string;
  copyright: string;
}

const COPY: Record<Lang, Copy> = {
  en: {
    overline: "Gym & studio training · iOS",
    h1a: "Notch is a coach ",
    h1b: "you talk to.",
    heroSub:
      "Bring a plan, or photograph one — a printed program, even a whiteboard — and Notch turns it into a real, structured workout. From there, every session is a conversation. Only got 6 reps instead of 8? Just say so — it adjusts and keeps going.",
    badge: "Coming soon to the App Store",
    betaNote: "In TestFlight beta — free during early access.",
    whatOverline: "What Notch is",
    whatBody:
      "It remembers everything, so you don't have to. Every weight, every set, every session, ready before you walk in.",
    howOverline: "How it works",
    s1t: "Photograph a plan",
    s1b: "A printed program or a whiteboard — Notch reads it into a structured workout.",
    s2t: "Talk through every set",
    s2b: "In plain language — confirm it, correct it, or just tell it what happened.",
    s3t: "Automatic progression",
    s3b: "Based on what you actually did last time.",
    studioOverline: "Studio",
    studioTitle: "Built for gym and studio training.",
    studioBody:
      "Most apps handle one or the other. Notch handles both. Lifting sessions track weight and reps, the way you'd expect. Studio and functional classes get their own units — band colour, box height, metres, calories, reps per side, rep ladders across rounds — tracked the way your coach actually calls them out.",
    st1t: "Blocks, not sets",
    st1b: "Numbered blocks stay numbered, in the order the coach wrote them.",
    st2t: "Scaling tiers",
    st2b: "The coach calls 40/45/50 — you pick your tier and the whole workout follows it.",
    st3t: "Real units",
    st3b: "Calories, metres, lengths and reps sit side by side, each measured the way the movement is.",
    st4t: "Ladders and stations",
    st4b: "Rep ladders and station rotations are kept whole, so what you log matches what you did.",
    shotsOverline: "Inside the app",
    skipToContent: "Skip to main content",
    langGroupLabel: "Choose language",
    shotsRegionLabel: "App screenshots — scroll horizontally to see more",
    footStatus: "Currently in TestFlight beta.",
    footContact: "Contact",
    footLegal: "Legal",
    privacy: "Privacy policy",
    terms: "Terms of use",
    accessibility: "Accessibility statement",
    copyright:
      "© 2026 Dor Haim Bobrutsky. Plans generated by AI — recommended to review with a certified trainer before starting.",
  },
  he: {
    overline: "אימוני חדר כושר וסטודיו · iOS",
    h1a: "Notch הוא מאמן ",
    h1b: "שמדברים איתו.",
    heroSub:
      "הביאו תוכנית, או צלמו אחת — תוכנית מודפסת, אפילו לוח מחיק — ו-Notch יהפוך אותה לאימון אמיתי ומסודר. משם, כל אימון הוא שיחה. יצאו 6 חזרות במקום 8? פשוט תגידו — הוא מתאים את עצמו וממשיך.",
    badge: "בקרוב ב-App Store",
    betaNote: "בבטא ב-TestFlight — חינם בתקופת ההשקה.",
    whatOverline: "מה זה Notch",
    whatBody: "הוא זוכר הכול, כדי שאתם לא תצטרכו. כל משקל, כל סט, כל אימון — מוכן לפני שנכנסתם לחדר.",
    howOverline: "איך זה עובד",
    s1t: "צלמו תוכנית",
    s1b: "תוכנית מודפסת או לוח מחיק — Notch קורא אותה והופך אותה לאימון מסודר.",
    s2t: "דברו על כל סט",
    s2b: "בשפה פשוטה — אשרו, תקנו, או פשוט תגידו מה קרה.",
    s3t: "התקדמות אוטומטית",
    s3b: "לפי מה שבאמת עשיתם בפעם הקודמת.",
    studioOverline: "סטודיו",
    studioTitle: "נבנה לאימוני חדר כושר וסטודיו.",
    studioBody:
      "רוב האפליקציות מטפלות באחד מהשניים. Notch מטפל בשניהם. אימוני משקולות עוקבים אחרי משקל וחזרות, כמו שמצפים. אימוני סטודיו ופונקציונלי מקבלים יחידות משל עצמם — צבע גומייה, גובה קופסה, מטרים, קלוריות, חזרות לכל צד, סולמות חזרות על פני סבבים — נמדדים בדיוק כמו שהמאמן מכריז עליהם.",
    st1t: "בלוקים, לא סטים",
    st1b: "בלוקים ממוספרים נשארים ממוספרים, בסדר שבו המאמן כתב אותם.",
    st2t: "רמות סקיילינג",
    st2b: "המאמן מכריז 40/45/50 — אתם בוחרים רמה וכל האימון הולך לפיה.",
    st3t: "יחידות אמיתיות",
    st3b: "קלוריות, מטרים, אורכי בריכה וחזרות זה לצד זה, כל אחד נמדד כמו שהתרגיל נמדד.",
    st4t: "סולמות ותחנות",
    st4b: "סולמות חזרות וסבבי תחנות נשמרים שלמים, כך שמה שנרשם הוא מה שבאמת עשיתם.",
    shotsOverline: "בתוך האפליקציה",
    skipToContent: "דלגו לתוכן הראשי",
    langGroupLabel: "בחירת שפה",
    shotsRegionLabel: "צילומי מסך מהאפליקציה — גללו לצדדים לצפייה בעוד",
    footStatus: "כרגע בבטא ב-TestFlight.",
    footContact: "יצירת קשר",
    footLegal: "משפטי",
    privacy: "מדיניות פרטיות",
    terms: "תנאי שימוש",
    accessibility: "הצהרת נגישות",
    copyright: "© 2026 Dor Haim Bobrutsky. התוכניות נוצרות על ידי AI — מומלץ לעבור עליהן עם מאמן מוסמך לפני שמתחילים.",
  },
};

const HERO_SHOT = { src: "/hero-coach-chat.png", width: 1242, height: 1882 };

const SHOTS: { src: string; width: number; height: number; alt: { en: string; he: string } }[] = [
  {
    src: "/shot-photo-plan.png",
    width: 1242,
    height: 2688,
    alt: {
      en: "Snap the board. Start training. — photographing a handwritten workout board",
      he: "מתמונה לתוכנית — צילום לוח אימונים כתוב ביד",
    },
  },
  {
    src: "/shot-studio-form.png",
    width: 1242,
    height: 1707,
    alt: {
      en: "Studio form — reps-per-side picker built for studio and functional training",
      he: "סטודיו — בורר חזרות לכל צד, בנוי לאימוני סטודיו ופונקציונלי",
    },
  },
  {
    src: "/shot-remembers.png",
    width: 1242,
    height: 2688,
    alt: {
      en: "No more scrolling back through your notes — every exercise remembers where you left off",
      he: "בלי לגלול אחורה בהערות — כל תרגיל זוכר איפה עצרתם",
    },
  },
  {
    src: "/shot-multilingual.png",
    width: 1242,
    height: 2688,
    alt: {
      en: "Multilingual — coaches you in your own language, not translated buttons",
      he: "רב-לשוני — מאמן אתכם בשפה שלכם, לא כפתורים מתורגמים",
    },
  },
];

function AppleMark() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="var(--text-primary)" aria-hidden="true">
      <path d="M16.365 1.43c0 1.14-.415 2.11-1.246 2.91-.997.96-2.19 1.51-3.09 1.43-.12-1.11.41-2.25 1.2-3 .84-.8 2.31-1.4 3.13-1.34.02.01.006 0 0 0zM20.7 17.2c-.5 1.16-1.09 2.28-1.87 3.32-1.06 1.42-2.16 2.83-3.9 2.86-1.71.03-2.26-1-4.22-1-1.96 0-2.57.97-4.19 1.03-1.67.06-2.94-1.53-4.02-2.93C.4 17.68-1.05 12.4 1.02 8.86c1.02-1.76 2.85-2.87 4.83-2.9 1.62-.03 3.15 1.09 4.14 1.09.98 0 2.84-1.35 4.79-1.15.82.03 3.11.33 4.58 2.5-.12.08-2.74 1.6-2.71 4.77.03 3.79 3.32 5.05 3.36 5.06-.03.09-.53 1.8-1.31 3.02z" />
    </svg>
  );
}

export default function Home() {
  const [lang, setLang] = useState<Lang>("en");
  const t = COPY[lang];
  const dir = lang === "he" ? "rtl" : "ltr";
  const shotsRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (shotsRef.current) shotsRef.current.scrollLeft = 0;
  }, [lang]);

  return (
    <div lang={lang} dir={dir} className={`${styles.landing} ${rubik.variable} ${plexMono.variable}`}>
      <a href="#main-content" className={styles.skipLink}>
        {t.skipToContent}
      </a>
      <header className={styles.header}>
        <div className={styles.logoRow}>
          <img src="/notch-mark.svg" alt="Notch" width={64} height={64} className={styles.logoMark} />
          <span className={styles.logoText}>Notch</span>
        </div>
        <div className={styles.langToggle} role="group" aria-label={t.langGroupLabel}>
          <button
            type="button"
            lang="en"
            aria-pressed={lang === "en"}
            onClick={() => setLang("en")}
            className={`${styles.langBtn} ${lang === "en" ? styles.langBtnActive : ""}`}
          >
            English
          </button>
          <button
            type="button"
            lang="he"
            aria-pressed={lang === "he"}
            onClick={() => setLang("he")}
            className={`${styles.langBtn} ${lang === "he" ? styles.langBtnActive : ""}`}
          >
            עברית
          </button>
        </div>
      </header>

      <main id="main-content">
      <section className={styles.hero}>
        <div className={styles.heroText}>
          <div className={styles.overline}>{t.overline}</div>
          <h1 className={styles.h1}>
            {t.h1a}
            <span className={styles.h1Accent}>{t.h1b}</span>
          </h1>
          <p className={styles.heroSub}>{t.heroSub}</p>
          <div className={styles.heroActions}>
            <div className={styles.badge}>
              <AppleMark />
              <span className={styles.badgeText}>{t.badge}</span>
            </div>
            <span className={styles.betaNote}>{t.betaNote}</span>
          </div>
        </div>
        <div className={styles.heroVisual}>
          <Image
            src={HERO_SHOT.src}
            width={HERO_SHOT.width}
            height={HERO_SHOT.height}
            alt={lang === "he" ? "האפליקציה — צ'אט עם המאמן" : "Notch mid-conversation — the coach chat screen"}
            className={styles.heroImg}
            sizes="(max-width: 640px) 62vw, 307px"
            priority
          />
        </div>
      </section>

      <section className={styles.section}>
        <div className={styles.sectionInner}>
          <div className={styles.sectionOverline}>{t.whatOverline}</div>
          <p className={styles.whatBody}>{t.whatBody}</p>
        </div>
      </section>

      <section className={styles.section}>
        <div className={styles.sectionInner}>
          <div className={styles.sectionOverline}>{t.howOverline}</div>
          <div className={styles.grid3}>
            <div>
              <div className={styles.stepNum}>01</div>
              <h3 className={styles.stepTitle}>{t.s1t}</h3>
              <p className={styles.stepBody}>{t.s1b}</p>
            </div>
            <div>
              <div className={styles.stepNum}>02</div>
              <h3 className={styles.stepTitle}>{t.s2t}</h3>
              <p className={styles.stepBody}>{t.s2b}</p>
            </div>
            <div>
              <div className={styles.stepNum}>03</div>
              <h3 className={styles.stepTitle}>{t.s3t}</h3>
              <p className={styles.stepBody}>{t.s3b}</p>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.section}>
        <div className={styles.sectionInner}>
          <div className={styles.sectionOverline}>{t.studioOverline}</div>
          <h2 className={styles.studioTitle}>{t.studioTitle}</h2>
          <p className={styles.studioBody}>{t.studioBody}</p>
          <div className={styles.grid4}>
            <div>
              <h3 className={styles.studioItemTitle}>{t.st1t}</h3>
              <p className={styles.studioItemBody}>{t.st1b}</p>
            </div>
            <div>
              <h3 className={styles.studioItemTitle}>{t.st2t}</h3>
              <p className={styles.studioItemBody}>{t.st2b}</p>
            </div>
            <div>
              <h3 className={styles.studioItemTitle}>{t.st3t}</h3>
              <p className={styles.studioItemBody}>{t.st3b}</p>
            </div>
            <div>
              <h3 className={styles.studioItemTitle}>{t.st4t}</h3>
              <p className={styles.studioItemBody}>{t.st4b}</p>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.section}>
        <div className={styles.sectionInner}>
          <div className={styles.sectionOverline}>{t.shotsOverline}</div>
          <div
            ref={shotsRef}
            className={styles.shotsWrap}
            dir="ltr"
            style={{ flexDirection: dir === "rtl" ? "row-reverse" : "row" }}
            role="group"
            aria-label={t.shotsRegionLabel}
            tabIndex={0}
          >
            {SHOTS.map((shot) => (
              <div className={styles.shotCard} dir={dir} key={shot.src}>
                <Image
                  src={shot.src}
                  width={shot.width}
                  height={shot.height}
                  alt={shot.alt[lang]}
                  className={styles.shotImg}
                  sizes="(max-width: 640px) 58vw, 260px"
                  loading="lazy"
                />
              </div>
            ))}
          </div>
        </div>
      </section>
      </main>

      <footer className={styles.footer}>
        <div className={styles.footerInner}>
          <div className={styles.footerBrand}>
            <div className={styles.footerBrandRow}>
              <img src="/notch-mark.svg" alt="" width={48} height={48} className={styles.footerLogoMark} />
              <span className={styles.footerBrandName}>Notch Fitness</span>
            </div>
            <div className={styles.footerStatus}>{t.footStatus}</div>
          </div>
          <div className={styles.footerCol}>
            <div className={styles.footerColTitle}>{t.footContact}</div>
            <a href="mailto:dorhaimbob@gmail.com" className={styles.footerLink}>
              dorhaimbob@gmail.com
            </a>
          </div>
          <nav className={styles.footerCol} aria-label={t.footLegal}>
            <div className={styles.footerColTitle}>{t.footLegal}</div>
            <a href="/privacy" className={styles.footerLink}>
              {t.privacy}
            </a>
            <a href="/terms" className={styles.footerLink}>
              {t.terms}
            </a>
            <a href="/accessibility" className={styles.footerLink}>
              {t.accessibility}
            </a>
          </nav>
        </div>
        <div className={styles.copyright}>{t.copyright}</div>
      </footer>
    </div>
  );
}
